INSERT INTO categories (id, name, parent_id)
VALUES (1, 'Antiques & collectables'),
	(2, 'Baby gear'),
	(3, 'Books'),
	(4, 'Building & renovation'),
	(5, 'Business, farming & industry'),
	(6, 'Clothing, Fashion'),
	(7, 'Computers & Electronics'),
	(8, 'Gaming'),
	(9, 'Health, beauty'),
	(10, 'Home, living'),
	(11, 'Jewellery, watches'),
	(12, 'Mobile phones'),
	(13, 'Music, instruments'),
	(14, 'Pets, animals'),
	(15, 'Sports'),
	(16, 'Toys, models'),
	(17, 'Advertising', 1),
	(18, 'Alcohol related', 1),
	(19, 'Appliances', 1),
	(20, 'Art deco & retro', 1),
	(21, 'Automotive & transport', 1),
	(22, 'Banknotes', 1),
	(23, 'Bottles', 1),
	(24, 'Clocks & scientific instruments', 1),
	(25, 'Coins', 1),
	(26, 'Cultural & ethnic', 1),
	(27, 'Documents & maps', 1),
	(28, 'Flags', 1),
	(29, 'Food & drink', 1),
	(30, 'Furniture & woodenware', 1),
	(31, 'Jewellery', 1),
	(32, 'Militaria', 1),
	(33, 'Movie & TV memorabilia', 1),
	(34, 'Museum pieces & artifacts', 1),
	(35, 'New Zealand & Maori', 1),
	(36, 'Ornaments & figurines', 1),
	(37, 'Phonecards', 1),
	(38, 'Pins, badges & patches', 1),
	(39, 'Postcards & writing', 1),
	(40, '3D Printers & Supplies', 7),
	(41, 'Blank discs & cases', 7),
	(42, 'Cables & adaptors', 7),
	(43, 'Components', 7),
	(44, 'Computer furniture', 7),
	(45, 'Desktops', 7),
	(46, 'Domain names', 7),
	(47, 'External storage', 7),
	(48, 'Laptops', 7),
	(49, 'Monitors', 7),
	(50, 'Networking & modems', 7),
	(51, 'Peripherals', 7),
	(52, 'Printer accessories & supplies', 7),
	(53, 'Printers', 7),
	(54, 'Servers', 7),
	(55, 'Software', 7),
	(56, 'Tablets & E-book readers', 7),
	(57, 'Vintage', 7),
	(58, 'Other', 7);