POST /api/listings HTTP/1.1
Host: localhost:5001
Content-Type: application/json

{
	"listing": {
		"titleCategory": {
			"title": "This is my title",
			"categoryId": 24,
			"subTitle": "afasfsdf",
			"endDate": "2024-09-02"
		},
		"itemDetails": {
			"condition": false,
			"description": "test 1235"
		},
		"photos": {
			"images": [],
			"heroImage": 0
		},
		"pricePayment": {
			"listingPrice": "10",
			"reservePrice": "10",
			"creditCardPayment": false,
			"bankTransferPayment": false,
			"bitcoinPayment": false
		},
		"shipping": {
			"pickUp": true,
			"shippingOption": "post"
		}
	}
}
