POST /api/listings HTTP/1.1
Host: localhost:5001
Content-Type: application/json

// {
// 	"listing": {
// 		"titleCategory": {
// 			"title": "This is my title",
// 			"categoryId": 24,
// 			"subCategoryId": 1,
// 			"subTitle": "afasfsdf",
// 			"endDate": "2024-09-02"
// 		},
// 		"itemDetails": {  
// 			"condition": false,
// 			"description": "test 1235"
// 		},
// 		"photos": {
// 			"images": [],
// 			"heroImage": 0
// 		},
// 		"pricePayment": {
// 			"listingPrice": "10",
// 			"reservePrice": "10",
// 			"creditCardPayment": false,
// 			"bankTransferPayment": false,
// 			"bitcoinPayment": false
// 		},
// 		"shipping": {
// 			"pickUp": true,
// 			"shippingOption": "post"
// 		}
// 	}
// }
// {
//     "listing": {
//         "titleCategory": {
//             "title": "",
//             "categoryId": 0,
//             "subCategoryId": 0,
//             "subTitle": "",
//             "endDate": "2024-09-01"
//         },
//         "itemDetails": {
//             "description": "",
//             "condition": false
//         },
//         "photos": {
//             "images": [],
//             "heroImage": 0
//         },
//         "pricePayment": {
//             "listingPrice": "",
//             "reservePrice": "",
//             "creditCardPayment": false,
//             "bankTransferPayment": false,
//             "bitcoinPayment": false
//         },
//         "shipping": {
//             "pickUp": true,
//             "shippingOption": "post"
//         }
//     }
// }

{
    "listing": {
        "titleCategory": {
            "title": "asdasd",
            "categoryId": 1,
            "subCategoryId": "17",
            "subTitle": "dddd",
            "endDate": "2024-09-01"
        },
        "itemDetails": {
            "description": "asdasdasdasdasd",
            "condition": "used"
        },
        "photos": {
            "images": [],
            "heroImage": 0
        },
        "pricePayment": {
            "listingPrice": "10",
            "reservePrice": "20",
            "creditCardPayment": false,
            "bankTransferPayment": false,
            "bitcoinPayment": false,
            "creditCard": true,
            "bankTransfer": true,
            "bitcoin": true
        },
        "shipping": {
            "pickUp": true,
            "shippingOption": "post"
        }
    }
}